### PR TITLE
Fix building with the official SDK paths

### PR DESCRIPTION
**Pull request by feilen**
Builds correctly when using the oculus-rift-sdk package, using only the official SDK (with static linkage to libOVR.a)

### CODE REVIEW

**Comment by ChristophHaag** [comment]
Looks like rebasing this on upstream master sucks a lot. Is vrpn going to include this in their master branch soon?

**Comment by feilen** [comment]
The plan right now seems to be to get rid of VRPN dependencies altogether.
Look at osvr-oculus-rift, branch 'no-vrpn-required'.

Even more helpfully, the developer working on that has mentioned he's
dedicate to making it work right on Linux, so, double good.

**Comment by ChristophHaag** [comment]
> Look at osvr-oculus-rift, branch 'no-vrpn-required'.

Does it actually do anything yet? I tried it, but the server segfaults as soon as any client connects.

**Comment by ChristophHaag** [comment]
I'm very confused with this..

vrpn_print_devices com_osvr_OculusRift/OculusRift0@localhost seems to work, but osvr_print_tree triggers a segfault here:

https://github.com/OSVR/OSVR-Oculus-Rift/blob/ecd7c11d86b0d3322dada541ea1b32c55c18d253/OculusRift.cpp#L267

Initially `hmd_` appears to work right, but when connecting with an OSVR client, the Oculus Rift gets added twice more and at the second time `hmd_` appears to be the first element in the struct it points to, so changing the hmd_ parameter to `(ovrHmd) &hmd_` should do the right thing...

Is it supposed to work right now? Was it tested on linux?

**Comment by feilen** [comment]
It's still not quite working I believe. My merge was just to get it
building with the official SDK.

**Comment by ChristophHaag** [comment]
I mean the segfaults are there with the no-vrpn-required branch does that. And this one don't use this vrpn version here at all, right?

The osvr-oculus-rift master branch doesn't cause cashes. I've also played with the master branch and OSVR-Tracker-Viewer a bit today. When starting with `OSVRTrackerView --pose /me/head` then uncommenting the debug output https://github.com/OSVR/OSVR-Tracker-Viewer/blob/2115743e78f85563c761401aba7c14916e0949a8/OSVRTrackerView.cpp#L67 and adding printing of `report->pose.rotation.data[0]` etc. does actually spit out some values that seem to be related to the rift position. The same works with `OSVRTrackerView --orientation /me/head`.

So I think the osvr-oculus-rift master branch actually works fine except for actually showing the position/orientation updates in the scene scene.

**Pull request merged**
